/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package facultymanagement;

/**
 *
 * @author Dimple
 */
public class Faculty_Workshop extends javax.swing.JFrame {

    /**
     * Creates new form Workshop
     */
    public Faculty_Workshop() {
        initComponents();
        
        tblWorkshop.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblWorkshop.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblWorkshop.getColumnModel().getColumn(2).setPreferredWidth(30);
        tblWorkshop.getColumnModel().getColumn(3).setPreferredWidth(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblWkName = new javax.swing.JLabel();
        lblWktitle = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        btnAddWkD = new com.k33ptoo.components.KButton();
        txtWkName = new javax.swing.JTextField();
        dtEndDate = new com.toedter.calendar.JDateChooser();
        dtStartDate = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        lblWktitle2 = new javax.swing.JLabel();
        scrlpaneWk = new javax.swing.JScrollPane();
        tblWorkshop = new javax.swing.JTable();
        btnDeleteWkD = new com.k33ptoo.components.KButton();
        btnUpdateWkD = new com.k33ptoo.components.KButton();
        jPanel1 = new javax.swing.JPanel();
        btnWorkshops = new com.k33ptoo.components.KButton();
        jPanel4 = new javax.swing.JPanel();
        btnDashboard = new com.k33ptoo.components.KButton();
        btnPublications = new com.k33ptoo.components.KButton();
        btnProfile = new com.k33ptoo.components.KButton();
        btnLogout = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1300, 900));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Faculty Management System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addGap(325, 325, 325))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        lblWkName.setText("Workshop Name");

        lblWktitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWktitle.setText("Add Workshop Details");

        lblStartDate.setText("Starting Date");

        lblEndDate.setText("End Date");

        btnAddWkD.setText("Add");
        btnAddWkD.setkBackGroundColor(new java.awt.Color(51, 51, 255));
        btnAddWkD.setkEndColor(new java.awt.Color(51, 51, 255));
        btnAddWkD.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        btnAddWkD.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAddWkD.setkHoverStartColor(new java.awt.Color(0, 51, 255));
        btnAddWkD.setkPressedColor(new java.awt.Color(0, 51, 204));
        btnAddWkD.setkSelectedColor(new java.awt.Color(0, 102, 255));
        btnAddWkD.setkStartColor(new java.awt.Color(0, 0, 204));
        btnAddWkD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWkDActionPerformed(evt);
            }
        });

        txtWkName.setName("txtwkname"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWkName, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWkName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(lblWktitle, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAddWkD, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblWktitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWkName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWkName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(dtStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(dtEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddWkD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblWktitle2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWktitle2.setText("Workshop Details");

        tblWorkshop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblWorkshop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sr. No.", "Name", "Start Date", "End Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWorkshop.setRowHeight(30);
        tblWorkshop.setShowGrid(true);
        tblWorkshop.getTableHeader().setResizingAllowed(false);
        tblWorkshop.getTableHeader().setReorderingAllowed(false);
        scrlpaneWk.setViewportView(tblWorkshop);
        if (tblWorkshop.getColumnModel().getColumnCount() > 0) {
            tblWorkshop.getColumnModel().getColumn(0).setResizable(false);
            tblWorkshop.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblWorkshop.getColumnModel().getColumn(1).setResizable(false);
            tblWorkshop.getColumnModel().getColumn(1).setPreferredWidth(30);
            tblWorkshop.getColumnModel().getColumn(2).setResizable(false);
            tblWorkshop.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblWorkshop.getColumnModel().getColumn(3).setResizable(false);
            tblWorkshop.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        btnDeleteWkD.setText("Delete");
        btnDeleteWkD.setkBackGroundColor(new java.awt.Color(51, 51, 255));
        btnDeleteWkD.setkEndColor(new java.awt.Color(51, 51, 255));
        btnDeleteWkD.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        btnDeleteWkD.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDeleteWkD.setkHoverStartColor(new java.awt.Color(0, 51, 255));
        btnDeleteWkD.setkPressedColor(new java.awt.Color(0, 51, 204));
        btnDeleteWkD.setkSelectedColor(new java.awt.Color(0, 102, 255));
        btnDeleteWkD.setkStartColor(new java.awt.Color(0, 0, 204));
        btnDeleteWkD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteWkDActionPerformed(evt);
            }
        });

        btnUpdateWkD.setText("Update");
        btnUpdateWkD.setkBackGroundColor(new java.awt.Color(51, 51, 255));
        btnUpdateWkD.setkEndColor(new java.awt.Color(51, 51, 255));
        btnUpdateWkD.setkHoverEndColor(new java.awt.Color(0, 102, 255));
        btnUpdateWkD.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdateWkD.setkHoverStartColor(new java.awt.Color(0, 51, 255));
        btnUpdateWkD.setkPressedColor(new java.awt.Color(0, 51, 204));
        btnUpdateWkD.setkSelectedColor(new java.awt.Color(0, 102, 255));
        btnUpdateWkD.setkStartColor(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(scrlpaneWk, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(lblWktitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUpdateWkD, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnDeleteWkD, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblWktitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(scrlpaneWk, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteWkD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateWkD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 900));

        btnWorkshops.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dimple\\Documents\\NetBeansProjects\\FacultyManagement\\src\\facultymanagement\\icons\\workshop (2).png")); // NOI18N
        btnWorkshops.setText("Workshops");
        btnWorkshops.setBorderPainted(false);
        btnWorkshops.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnWorkshops.setkBackGroundColor(new java.awt.Color(242, 242, 242));
        btnWorkshops.setkEndColor(new java.awt.Color(242, 242, 242));
        btnWorkshops.setkForeGround(new java.awt.Color(0, 0, 0));
        btnWorkshops.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        btnWorkshops.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnWorkshops.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        btnWorkshops.setkPressedColor(new java.awt.Color(0, 51, 204));
        btnWorkshops.setkSelectedColor(new java.awt.Color(0, 102, 204));
        btnWorkshops.setkStartColor(new java.awt.Color(255, 255, 255));
        btnWorkshops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkshopsActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        btnDashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dimple\\Documents\\NetBeansProjects\\FacultyManagement\\src\\facultymanagement\\icons\\home.png")); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorderPainted(false);
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setkBackGroundColor(new java.awt.Color(242, 242, 242));
        btnDashboard.setkEndColor(new java.awt.Color(242, 242, 242));
        btnDashboard.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDashboard.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        btnDashboard.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDashboard.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        btnDashboard.setkPressedColor(new java.awt.Color(0, 51, 204));
        btnDashboard.setkSelectedColor(new java.awt.Color(0, 102, 204));
        btnDashboard.setkStartColor(new java.awt.Color(255, 255, 255));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnPublications.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dimple\\Documents\\NetBeansProjects\\FacultyManagement\\src\\facultymanagement\\icons\\book (2).png")); // NOI18N
        btnPublications.setText("Publications");
        btnPublications.setBorderPainted(false);
        btnPublications.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPublications.setkBackGroundColor(new java.awt.Color(242, 242, 242));
        btnPublications.setkEndColor(new java.awt.Color(242, 242, 242));
        btnPublications.setkForeGround(new java.awt.Color(0, 0, 0));
        btnPublications.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        btnPublications.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnPublications.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        btnPublications.setkPressedColor(new java.awt.Color(0, 51, 204));
        btnPublications.setkSelectedColor(new java.awt.Color(0, 102, 204));
        btnPublications.setkStartColor(new java.awt.Color(255, 255, 255));
        btnPublications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicationsActionPerformed(evt);
            }
        });

        btnProfile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dimple\\Documents\\NetBeansProjects\\FacultyManagement\\src\\facultymanagement\\icons\\user.png")); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.setBorderPainted(false);
        btnProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProfile.setkBackGroundColor(new java.awt.Color(242, 242, 242));
        btnProfile.setkEndColor(new java.awt.Color(242, 242, 242));
        btnProfile.setkForeGround(new java.awt.Color(0, 0, 0));
        btnProfile.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        btnProfile.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnProfile.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        btnProfile.setkPressedColor(new java.awt.Color(0, 51, 204));
        btnProfile.setkSelectedColor(new java.awt.Color(0, 102, 204));
        btnProfile.setkStartColor(new java.awt.Color(255, 255, 255));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dimple\\Documents\\NetBeansProjects\\FacultyManagement\\src\\facultymanagement\\icons\\exit.png")); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorderPainted(false);
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setkBackGroundColor(new java.awt.Color(242, 242, 242));
        btnLogout.setkEndColor(new java.awt.Color(242, 242, 242));
        btnLogout.setkForeGround(new java.awt.Color(0, 0, 0));
        btnLogout.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        btnLogout.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnLogout.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        btnLogout.setkPressedColor(new java.awt.Color(0, 51, 204));
        btnLogout.setkSelectedColor(new java.awt.Color(0, 102, 204));
        btnLogout.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPublications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWorkshops, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnWorkshops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnPublications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWorkshopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkshopsActionPerformed
        this.setVisible(false);
        Faculty_Workshop wk = new Faculty_Workshop();
        wk.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnWorkshopsActionPerformed

    private void btnDeleteWkDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteWkDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteWkDActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
    this.setVisible(false);
    Faculty_Dashboard fc = new Faculty_Dashboard();
    fc.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnPublicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicationsActionPerformed
        this.setVisible(false);
        Faculty_Publications fp = new Faculty_Publications();
        fp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnPublicationsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        this.setVisible(false);
        Faculty_Profile fpr = new Faculty_Profile();
        fpr.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnAddWkDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWkDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddWkDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Faculty_Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Faculty_Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Faculty_Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Faculty_Workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Faculty_Workshop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAddWkD;
    private com.k33ptoo.components.KButton btnDashboard;
    private com.k33ptoo.components.KButton btnDeleteWkD;
    private com.k33ptoo.components.KButton btnLogout;
    private com.k33ptoo.components.KButton btnProfile;
    private com.k33ptoo.components.KButton btnPublications;
    private com.k33ptoo.components.KButton btnUpdateWkD;
    private com.k33ptoo.components.KButton btnWorkshops;
    private com.toedter.calendar.JDateChooser dtEndDate;
    private com.toedter.calendar.JDateChooser dtStartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblWkName;
    private javax.swing.JLabel lblWktitle;
    private javax.swing.JLabel lblWktitle2;
    private javax.swing.JScrollPane scrlpaneWk;
    private javax.swing.JTable tblWorkshop;
    private javax.swing.JTextField txtWkName;
    // End of variables declaration//GEN-END:variables
}
