/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package facultyhome;
import javax.swing.*;
import java.awt.CardLayout;
import java.sql.*;

/**
 *
 * @author saish
 */
public class AdminGUI extends JFrame {

    /**
     * Creates new form AdminGUI
     */
    CardLayout cardLayout;
    
    public AdminGUI() {
        initComponents();
        cardLayout = (CardLayout)(CardPanel.getLayout()); 
        SetProfile();
        
        
        
    }
    public void SetProfile()
    {
        LoginAdmin la = new LoginAdmin();
        String user=la.user;
        
        
        try
        {   
            //Creating Connection Object
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/management","root","root");
            //Prepared Statement
            PreparedStatement st = connection.prepareStatement("Select username,name,contact_no from admin_details WHERE username = ?");
            st.setString(1, user);
            
           ResultSet res = st.executeQuery();
           if(res.next())
           {
                profileUnameLabel.setText(res.getString(1));
                profileNameLabel.setText(res.getString(2));
                profileContactLabel.setText(res.getString(3));
           }
          

        }
        catch(SQLException e1)
        {
            e1.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        DashBoard7 = new com.k33ptoo.components.KButton();
        Logout7 = new com.k33ptoo.components.KButton();
        Add_Faculty7 = new com.k33ptoo.components.KButton();
        Manage_Faculty7 = new com.k33ptoo.components.KButton();
        Profile_Button7 = new com.k33ptoo.components.KButton();
        CardPanel = new javax.swing.JPanel();
        DashBoard = new javax.swing.JPanel();
        Right_Title1 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        ManageFaculty = new javax.swing.JPanel();
        Title = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Delete = new com.k33ptoo.components.KButton();
        Update = new com.k33ptoo.components.KButton();
        AddFaculty = new javax.swing.JPanel();
        Title1 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        New_Faculty = new javax.swing.JPanel();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        Id = new java.awt.TextField();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        First = new java.awt.TextField();
        Last = new java.awt.TextField();
        Email = new java.awt.TextField();
        Pass = new java.awt.TextField();
        Salary = new java.awt.TextField();
        label22 = new java.awt.Label();
        Address = new java.awt.TextField();
        label23 = new java.awt.Label();
        kButton1 = new com.k33ptoo.components.KButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox2 = new javax.swing.JComboBox<>();
        Profile = new javax.swing.JPanel();
        Right_Title = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        profileUnameLabel = new javax.swing.JLabel();
        profileContactLabel = new javax.swing.JLabel();
        profileNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 900));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        DashBoard7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DashBoard7.setForeground(new java.awt.Color(0, 0, 0));
        DashBoard7.setText("DashBoard");
        DashBoard7.setToolTipText("");
        DashBoard7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        DashBoard7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        DashBoard7.setkEndColor(new java.awt.Color(255, 255, 255));
        DashBoard7.setkForeGround(new java.awt.Color(0, 0, 0));
        DashBoard7.setkHoverColor(new java.awt.Color(0, 0, 0));
        DashBoard7.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        DashBoard7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        DashBoard7.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        DashBoard7.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        DashBoard7.setkStartColor(new java.awt.Color(255, 255, 255));
        DashBoard7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashBoard7ActionPerformed(evt);
            }
        });

        Logout7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logout7.setForeground(new java.awt.Color(0, 0, 0));
        Logout7.setText("Logout");
        Logout7.setToolTipText("");
        Logout7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Logout7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Logout7.setkEndColor(new java.awt.Color(255, 255, 255));
        Logout7.setkForeGround(new java.awt.Color(0, 0, 0));
        Logout7.setkHoverColor(new java.awt.Color(0, 0, 0));
        Logout7.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Logout7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Logout7.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Logout7.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Logout7.setkStartColor(new java.awt.Color(255, 255, 255));
        Logout7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout7ActionPerformed(evt);
            }
        });

        Add_Faculty7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Add_Faculty7.setForeground(new java.awt.Color(0, 0, 0));
        Add_Faculty7.setText("Add Faculty");
        Add_Faculty7.setToolTipText("");
        Add_Faculty7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Add_Faculty7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Add_Faculty7.setkEndColor(new java.awt.Color(255, 255, 255));
        Add_Faculty7.setkForeGround(new java.awt.Color(0, 0, 0));
        Add_Faculty7.setkHoverColor(new java.awt.Color(0, 0, 0));
        Add_Faculty7.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Add_Faculty7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Add_Faculty7.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Add_Faculty7.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Add_Faculty7.setkStartColor(new java.awt.Color(255, 255, 255));
        Add_Faculty7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Faculty7ActionPerformed(evt);
            }
        });

        Manage_Faculty7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Manage_Faculty7.setForeground(new java.awt.Color(0, 0, 0));
        Manage_Faculty7.setText("Manage Faculty");
        Manage_Faculty7.setToolTipText("");
        Manage_Faculty7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Manage_Faculty7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty7.setkEndColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty7.setkForeGround(new java.awt.Color(0, 0, 0));
        Manage_Faculty7.setkHoverColor(new java.awt.Color(0, 0, 0));
        Manage_Faculty7.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Manage_Faculty7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Manage_Faculty7.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Manage_Faculty7.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Manage_Faculty7.setkStartColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_Faculty7ActionPerformed(evt);
            }
        });

        Profile_Button7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Profile_Button7.setForeground(new java.awt.Color(0, 0, 0));
        Profile_Button7.setText("Profile");
        Profile_Button7.setToolTipText("");
        Profile_Button7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Profile_Button7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Profile_Button7.setkEndColor(new java.awt.Color(255, 255, 255));
        Profile_Button7.setkForeGround(new java.awt.Color(0, 0, 0));
        Profile_Button7.setkHoverColor(new java.awt.Color(0, 0, 0));
        Profile_Button7.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Profile_Button7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Profile_Button7.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Profile_Button7.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Profile_Button7.setkStartColor(new java.awt.Color(255, 255, 255));
        Profile_Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_Button7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DashBoard7, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(Add_Faculty7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Manage_Faculty7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Profile_Button7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Logout7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(DashBoard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Add_Faculty7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Manage_Faculty7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Profile_Button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 316, Short.MAX_VALUE))
        );

        CardPanel.setLayout(new java.awt.CardLayout());

        DashBoard.setBackground(new java.awt.Color(255, 255, 255));
        DashBoard.setPreferredSize(new java.awt.Dimension(1300, 900));

        Right_Title1.setPreferredSize(new java.awt.Dimension(1300, 130));

        label4.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        label4.setText("Faculty Managment System");

        javax.swing.GroupLayout Right_Title1Layout = new javax.swing.GroupLayout(Right_Title1);
        Right_Title1.setLayout(Right_Title1Layout);
        Right_Title1Layout.setHorizontalGroup(
            Right_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right_Title1Layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
        );
        Right_Title1Layout.setVerticalGroup(
            Right_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_Title1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DashBoardLayout = new javax.swing.GroupLayout(DashBoard);
        DashBoard.setLayout(DashBoardLayout);
        DashBoardLayout.setHorizontalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Right_Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DashBoardLayout.setVerticalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addComponent(Right_Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(770, Short.MAX_VALUE))
        );

        CardPanel.add(DashBoard, "card2");

        ManageFaculty.setBackground(new java.awt.Color(255, 255, 255));
        ManageFaculty.setPreferredSize(new java.awt.Dimension(1300, 900));

        Title.setPreferredSize(new java.awt.Dimension(1300, 130));

        label1.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        label1.setText("Faculty Managment System");

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Teacher's ID", "First Name", "Last Name", "Email_Id", "Date Of Birth", "Qualification", "Designation", "Joning Date", "Salary", "Address", "null", "Title 12"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(750, 500));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        Delete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Delete.setForeground(new java.awt.Color(0, 0, 0));
        Delete.setText("Delete");
        Delete.setToolTipText("");
        Delete.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Delete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Delete.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Delete.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Delete.setkEndColor(new java.awt.Color(255, 255, 255));
        Delete.setkForeGround(new java.awt.Color(0, 0, 0));
        Delete.setkHoverColor(new java.awt.Color(0, 0, 0));
        Delete.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Delete.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Delete.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Delete.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Delete.setkStartColor(new java.awt.Color(255, 255, 255));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Update.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Update.setForeground(new java.awt.Color(0, 0, 0));
        Update.setText("Update");
        Update.setToolTipText("");
        Update.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Update.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Update.setkEndColor(new java.awt.Color(255, 255, 255));
        Update.setkForeGround(new java.awt.Color(0, 0, 0));
        Update.setkHoverColor(new java.awt.Color(0, 0, 0));
        Update.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Update.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Update.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Update.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Update.setkStartColor(new java.awt.Color(255, 255, 255));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageFacultyLayout = new javax.swing.GroupLayout(ManageFaculty);
        ManageFaculty.setLayout(ManageFacultyLayout);
        ManageFacultyLayout.setHorizontalGroup(
            ManageFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageFacultyLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(ManageFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageFacultyLayout.createSequentialGroup()
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289)))
                .addGap(38, 38, 38))
        );
        ManageFacultyLayout.setVerticalGroup(
            ManageFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageFacultyLayout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ManageFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );

        CardPanel.add(ManageFaculty, "card3");

        AddFaculty.setBackground(new java.awt.Color(255, 255, 255));
        AddFaculty.setPreferredSize(new java.awt.Dimension(1300, 900));

        Title1.setPreferredSize(new java.awt.Dimension(1300, 130));

        label2.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        label2.setText("Faculty Managment System");

        javax.swing.GroupLayout Title1Layout = new javax.swing.GroupLayout(Title1);
        Title1.setLayout(Title1Layout);
        Title1Layout.setHorizontalGroup(
            Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Title1Layout.createSequentialGroup()
                .addGap(0, 384, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
        );
        Title1Layout.setVerticalGroup(
            Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Title1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jScrollPane2.setPreferredSize(new java.awt.Dimension(700, 600));

        New_Faculty.setBackground(new java.awt.Color(255, 255, 255));
        New_Faculty.setPreferredSize(new java.awt.Dimension(1300, 1050));

        label12.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label12.setText("Add New Faculty");

        label13.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label13.setText("Teacher's ID:");

        Id.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        label14.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label14.setText("First Name:");

        label15.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label15.setText("Last Name:");

        label16.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label16.setText("Email_Id");

        label17.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label17.setText("Password:");

        label18.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label18.setText("Date of Birth:");

        label19.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label19.setText("Joining Date:");

        label20.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label20.setText("Designation:");

        label21.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label21.setText("Qualification:");

        First.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        Last.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        Email.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        Pass.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        Salary.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryActionPerformed(evt);
            }
        });

        label22.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label22.setText("Salary:");

        Address.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });

        label23.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label23.setText("Address");

        kButton1.setText("Add Faculty");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jDateChooser2.setDateFormatString("yyyy-MM-dd");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout New_FacultyLayout = new javax.swing.GroupLayout(New_Faculty);
        New_Faculty.setLayout(New_FacultyLayout);
        New_FacultyLayout.setHorizontalGroup(
            New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, New_FacultyLayout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addGroup(New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Last, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(First, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(404, 404, 404))
            .addGroup(New_FacultyLayout.createSequentialGroup()
                .addGroup(New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(New_FacultyLayout.createSequentialGroup()
                        .addGap(552, 552, 552)
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(New_FacultyLayout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        New_FacultyLayout.setVerticalGroup(
            New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(New_FacultyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(First, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jScrollPane2.setViewportView(New_Faculty);

        javax.swing.GroupLayout AddFacultyLayout = new javax.swing.GroupLayout(AddFaculty);
        AddFaculty.setLayout(AddFacultyLayout);
        AddFacultyLayout.setHorizontalGroup(
            AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddFacultyLayout.setVerticalGroup(
            AddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddFacultyLayout.createSequentialGroup()
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        CardPanel.add(AddFaculty, "card4");

        Profile.setBackground(new java.awt.Color(255, 255, 255));
        Profile.setPreferredSize(new java.awt.Dimension(1300, 900));

        Right_Title.setPreferredSize(new java.awt.Dimension(1300, 130));

        label3.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        label3.setText("Faculty Managment System");

        javax.swing.GroupLayout Right_TitleLayout = new javax.swing.GroupLayout(Right_Title);
        Right_Title.setLayout(Right_TitleLayout);
        Right_TitleLayout.setHorizontalGroup(
            Right_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right_TitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
        );
        Right_TitleLayout.setVerticalGroup(
            Right_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_TitleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Profile");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Contact no");

        kButton2.setText("Change Password");

        kButton3.setText("Edit Profile");

        profileUnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        profileContactLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        profileNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(profileContactLabel)
                                    .addComponent(profileUnameLabel)
                                    .addComponent(profileNameLabel)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(kButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(profileUnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(profileNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(profileContactLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Right_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(454, 454, 454)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(494, Short.MAX_VALUE))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addComponent(Right_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        CardPanel.add(Profile, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashBoard7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBoard7ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(CardPanel, "card2");
    }//GEN-LAST:event_DashBoard7ActionPerformed

    private void Logout7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout7ActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
          new Home().setVisible(true);
    }//GEN-LAST:event_Logout7ActionPerformed

    private void Add_Faculty7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Faculty7ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(CardPanel, "card4");
    }//GEN-LAST:event_Add_Faculty7ActionPerformed

    private void Manage_Faculty7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Faculty7ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(CardPanel, "card3");
    }//GEN-LAST:event_Manage_Faculty7ActionPerformed

    private void Profile_Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_Button7ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(CardPanel, "card5");
//        SetProfile();

        
        
    }//GEN-LAST:event_Profile_Button7ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddFaculty;
    private com.k33ptoo.components.KButton Add_Faculty7;
    private java.awt.TextField Address;
    private javax.swing.JPanel CardPanel;
    private javax.swing.JPanel DashBoard;
    private com.k33ptoo.components.KButton DashBoard7;
    private com.k33ptoo.components.KButton Delete;
    private java.awt.TextField Email;
    private java.awt.TextField First;
    private java.awt.TextField Id;
    private java.awt.TextField Last;
    private com.k33ptoo.components.KButton Logout7;
    private javax.swing.JPanel ManageFaculty;
    private com.k33ptoo.components.KButton Manage_Faculty7;
    private javax.swing.JPanel New_Faculty;
    private java.awt.TextField Pass;
    private javax.swing.JPanel Profile;
    private com.k33ptoo.components.KButton Profile_Button7;
    private javax.swing.JPanel Right_Title;
    private javax.swing.JPanel Right_Title1;
    private java.awt.TextField Salary;
    private javax.swing.JPanel Title;
    private javax.swing.JPanel Title1;
    private com.k33ptoo.components.KButton Update;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private java.awt.Label label1;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JLabel profileContactLabel;
    private javax.swing.JLabel profileNameLabel;
    private javax.swing.JLabel profileUnameLabel;
    // End of variables declaration//GEN-END:variables
}
