/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package faculty;

/**
 *
 * @author HP
 */
public class Add_Faculty extends javax.swing.JFrame {

    /**
     * Creates new form Add_Faculty
     */
    public Add_Faculty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Right_Panel = new javax.swing.JPanel();
        Title = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        New_Faculty = new javax.swing.JPanel();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        Id = new java.awt.TextField();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        First = new java.awt.TextField();
        Last = new java.awt.TextField();
        Email = new java.awt.TextField();
        Pass = new java.awt.TextField();
        DOB = new java.awt.TextField();
        Quali = new java.awt.TextField();
        Desig = new java.awt.TextField();
        Joining_date = new java.awt.TextField();
        Salary = new java.awt.TextField();
        label22 = new java.awt.Label();
        Address = new java.awt.TextField();
        label23 = new java.awt.Label();
        Left_Panel = new javax.swing.JPanel();
        DashBoard = new com.k33ptoo.components.KButton();
        Logout = new com.k33ptoo.components.KButton();
        Add_Faculty = new com.k33ptoo.components.KButton();
        Manage_Faculty = new com.k33ptoo.components.KButton();
        Profile_Button = new com.k33ptoo.components.KButton();
        Left_top = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 900));
        setResizable(false);

        Right_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Right_Panel.setPreferredSize(new java.awt.Dimension(1300, 900));

        Title.setPreferredSize(new java.awt.Dimension(1300, 200));

        label1.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        label1.setText("Faculty Managment System");

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 100));

        New_Faculty.setPreferredSize(new java.awt.Dimension(700, 1750));

        label12.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label12.setText("Add New Faculty");

        label13.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label13.setText("Teacher's ID:");

        Id.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        label14.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label14.setText("First Name:");

        label15.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label15.setText("Last Name:");

        label16.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label16.setText("Email_Id");

        label17.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label17.setText("Password:");

        label18.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label18.setText("Date of Birth:");

        label19.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label19.setText("Joining Date:");

        label20.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label20.setText("Designation:");

        label21.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label21.setText("Qualification:");

        First.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        Last.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        Email.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        Pass.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        DOB.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        Quali.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N

        Desig.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Desig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesigActionPerformed(evt);
            }
        });

        Joining_date.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Joining_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Joining_dateActionPerformed(evt);
            }
        });

        Salary.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryActionPerformed(evt);
            }
        });

        label22.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label22.setText("Salary:");

        Address.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });

        label23.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label23.setText("Address");

        javax.swing.GroupLayout New_FacultyLayout = new javax.swing.GroupLayout(New_Faculty);
        New_Faculty.setLayout(New_FacultyLayout);
        New_FacultyLayout.setHorizontalGroup(
            New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(New_FacultyLayout.createSequentialGroup()
                .addGroup(New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(New_FacultyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(New_FacultyLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(Desig, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                                .addComponent(Quali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(First, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Last, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Joining_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(New_FacultyLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(New_FacultyLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(New_FacultyLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(New_FacultyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(New_FacultyLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(New_FacultyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(New_FacultyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
        );
        New_FacultyLayout.setVerticalGroup(
            New_FacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(New_FacultyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(First, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(Last, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Quali, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desig, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Joining_date, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(533, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(New_Faculty);

        javax.swing.GroupLayout Right_PanelLayout = new javax.swing.GroupLayout(Right_Panel);
        Right_Panel.setLayout(Right_PanelLayout);
        Right_PanelLayout.setHorizontalGroup(
            Right_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1301, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right_PanelLayout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
        );
        Right_PanelLayout.setVerticalGroup(
            Right_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        Left_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Left_Panel.setPreferredSize(new java.awt.Dimension(300, 900));

        DashBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DashBoard.setForeground(new java.awt.Color(0, 0, 0));
        DashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home (1).png"))); // NOI18N
        DashBoard.setText("DashBoard");
        DashBoard.setToolTipText("");
        DashBoard.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        DashBoard.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        DashBoard.setkEndColor(new java.awt.Color(255, 255, 255));
        DashBoard.setkForeGround(new java.awt.Color(0, 0, 0));
        DashBoard.setkHoverColor(new java.awt.Color(0, 0, 0));
        DashBoard.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        DashBoard.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        DashBoard.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        DashBoard.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        DashBoard.setkStartColor(new java.awt.Color(255, 255, 255));
        DashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashBoardActionPerformed(evt);
            }
        });

        Logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logout.setForeground(new java.awt.Color(0, 0, 0));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.setToolTipText("");
        Logout.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Logout.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Logout.setkEndColor(new java.awt.Color(255, 255, 255));
        Logout.setkForeGround(new java.awt.Color(0, 0, 0));
        Logout.setkHoverColor(new java.awt.Color(0, 0, 0));
        Logout.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Logout.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Logout.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Logout.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Logout.setkStartColor(new java.awt.Color(255, 255, 255));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Add_Faculty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Add_Faculty.setForeground(new java.awt.Color(0, 0, 0));
        Add_Faculty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        Add_Faculty.setText("Add Faculty");
        Add_Faculty.setToolTipText("");
        Add_Faculty.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Add_Faculty.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Add_Faculty.setkEndColor(new java.awt.Color(255, 255, 255));
        Add_Faculty.setkForeGround(new java.awt.Color(0, 0, 0));
        Add_Faculty.setkHoverColor(new java.awt.Color(0, 0, 0));
        Add_Faculty.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Add_Faculty.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Add_Faculty.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Add_Faculty.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Add_Faculty.setkStartColor(new java.awt.Color(255, 255, 255));
        Add_Faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_FacultyActionPerformed(evt);
            }
        });

        Manage_Faculty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Manage_Faculty.setForeground(new java.awt.Color(0, 0, 0));
        Manage_Faculty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/project-management.png"))); // NOI18N
        Manage_Faculty.setText("Manage Faculty");
        Manage_Faculty.setToolTipText("");
        Manage_Faculty.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Manage_Faculty.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty.setkEndColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty.setkForeGround(new java.awt.Color(0, 0, 0));
        Manage_Faculty.setkHoverColor(new java.awt.Color(0, 0, 0));
        Manage_Faculty.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Manage_Faculty.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Manage_Faculty.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Manage_Faculty.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Manage_Faculty.setkStartColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_FacultyActionPerformed(evt);
            }
        });

        Profile_Button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Profile_Button.setForeground(new java.awt.Color(0, 0, 0));
        Profile_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        Profile_Button.setText("Profile");
        Profile_Button.setToolTipText("");
        Profile_Button.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Profile_Button.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Profile_Button.setkEndColor(new java.awt.Color(255, 255, 255));
        Profile_Button.setkForeGround(new java.awt.Color(0, 0, 0));
        Profile_Button.setkHoverColor(new java.awt.Color(0, 0, 0));
        Profile_Button.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Profile_Button.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Profile_Button.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Profile_Button.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Profile_Button.setkStartColor(new java.awt.Color(255, 255, 255));
        Profile_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButtonActionPerformed(evt);
            }
        });

        Left_top.setBackground(new java.awt.Color(75, 86, 210));
        Left_top.setPreferredSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout Left_topLayout = new javax.swing.GroupLayout(Left_top);
        Left_top.setLayout(Left_topLayout);
        Left_topLayout.setHorizontalGroup(
            Left_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Left_topLayout.setVerticalGroup(
            Left_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Left_PanelLayout = new javax.swing.GroupLayout(Left_Panel);
        Left_Panel.setLayout(Left_PanelLayout);
        Left_PanelLayout.setHorizontalGroup(
            Left_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Left_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Manage_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profile_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(Left_top, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );
        Left_PanelLayout.setVerticalGroup(
            Left_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left_PanelLayout.createSequentialGroup()
                .addComponent(Left_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(DashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Add_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Manage_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Profile_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(583, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Left_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Right_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Right_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1553, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Left_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryActionPerformed

    private void Joining_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Joining_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Joining_dateActionPerformed

    private void DesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesigActionPerformed

    private void DashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashBoardActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void Add_FacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_FacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_FacultyActionPerformed

    private void Manage_FacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_FacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_FacultyActionPerformed

    private void Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Faculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Add_Faculty;
    private java.awt.TextField Address;
    private java.awt.TextField DOB;
    private com.k33ptoo.components.KButton DashBoard;
    private java.awt.TextField Desig;
    private java.awt.TextField Email;
    private java.awt.TextField First;
    private java.awt.TextField Id;
    private java.awt.TextField Joining_date;
    private java.awt.TextField Last;
    private javax.swing.JPanel Left_Panel;
    private javax.swing.JPanel Left_top;
    private com.k33ptoo.components.KButton Logout;
    private com.k33ptoo.components.KButton Manage_Faculty;
    private javax.swing.JPanel New_Faculty;
    private java.awt.TextField Pass;
    private com.k33ptoo.components.KButton Profile_Button;
    private java.awt.TextField Quali;
    private javax.swing.JPanel Right_Panel;
    private java.awt.TextField Salary;
    private javax.swing.JPanel Title;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    // End of variables declaration//GEN-END:variables
}
