/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package faculty;

/**
 *
 * @author HP
 */
public class Manage_Faculty extends javax.swing.JFrame {

    /**
     * Creates new form Manage_Faculty
     */
    public Manage_Faculty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Right_Panel = new javax.swing.JPanel();
        Title = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Delete = new com.k33ptoo.components.KButton();
        Update = new com.k33ptoo.components.KButton();
        Left_Panel7 = new javax.swing.JPanel();
        DashBoard7 = new com.k33ptoo.components.KButton();
        Logout7 = new com.k33ptoo.components.KButton();
        Add_Faculty7 = new com.k33ptoo.components.KButton();
        Manage_Faculty7 = new com.k33ptoo.components.KButton();
        Profile_Button7 = new com.k33ptoo.components.KButton();
        Left_top7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 900));

        Right_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Right_Panel.setPreferredSize(new java.awt.Dimension(1300, 900));

        Title.setPreferredSize(new java.awt.Dimension(1300, 200));

        label1.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        label1.setText("Faculty Managment System");

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Teacher's ID", "First Name", "Last Name", "Email_Id", "Date Of Birth", "Qualification", "Designation", "Joning Date", "Salary", "Address", "null", "Title 12"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(750, 500));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        Delete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Delete.setForeground(new java.awt.Color(0, 0, 0));
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        Delete.setText("Delete");
        Delete.setToolTipText("");
        Delete.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Delete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Delete.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Delete.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Delete.setkEndColor(new java.awt.Color(255, 255, 255));
        Delete.setkForeGround(new java.awt.Color(0, 0, 0));
        Delete.setkHoverColor(new java.awt.Color(0, 0, 0));
        Delete.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Delete.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Delete.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Delete.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Delete.setkStartColor(new java.awt.Color(255, 255, 255));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Update.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Update.setForeground(new java.awt.Color(0, 0, 0));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        Update.setText("Update");
        Update.setToolTipText("");
        Update.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Update.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Update.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Update.setkEndColor(new java.awt.Color(255, 255, 255));
        Update.setkForeGround(new java.awt.Color(0, 0, 0));
        Update.setkHoverColor(new java.awt.Color(0, 0, 0));
        Update.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Update.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Update.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Update.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Update.setkStartColor(new java.awt.Color(255, 255, 255));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Right_PanelLayout = new javax.swing.GroupLayout(Right_Panel);
        Right_Panel.setLayout(Right_PanelLayout);
        Right_PanelLayout.setHorizontalGroup(
            Right_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Right_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Right_PanelLayout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right_PanelLayout.createSequentialGroup()
                        .addGap(0, 87, Short.MAX_VALUE)
                        .addGroup(Right_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right_PanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right_PanelLayout.createSequentialGroup()
                                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(330, 330, 330))))))
        );
        Right_PanelLayout.setVerticalGroup(
            Right_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Right_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(452, Short.MAX_VALUE))
        );

        Left_Panel7.setBackground(new java.awt.Color(255, 255, 255));
        Left_Panel7.setPreferredSize(new java.awt.Dimension(300, 900));

        DashBoard7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DashBoard7.setForeground(new java.awt.Color(0, 0, 0));
        DashBoard7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home (1).png"))); // NOI18N
        DashBoard7.setText("DashBoard");
        DashBoard7.setToolTipText("");
        DashBoard7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        DashBoard7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        DashBoard7.setkEndColor(new java.awt.Color(255, 255, 255));
        DashBoard7.setkForeGround(new java.awt.Color(0, 0, 0));
        DashBoard7.setkHoverColor(new java.awt.Color(0, 0, 0));
        DashBoard7.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        DashBoard7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        DashBoard7.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        DashBoard7.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        DashBoard7.setkStartColor(new java.awt.Color(255, 255, 255));
        DashBoard7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashBoard7ActionPerformed(evt);
            }
        });

        Logout7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logout7.setForeground(new java.awt.Color(0, 0, 0));
        Logout7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        Logout7.setText("Logout");
        Logout7.setToolTipText("");
        Logout7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Logout7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Logout7.setkEndColor(new java.awt.Color(255, 255, 255));
        Logout7.setkForeGround(new java.awt.Color(0, 0, 0));
        Logout7.setkHoverColor(new java.awt.Color(0, 0, 0));
        Logout7.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Logout7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Logout7.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Logout7.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Logout7.setkStartColor(new java.awt.Color(255, 255, 255));
        Logout7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout7ActionPerformed(evt);
            }
        });

        Add_Faculty7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Add_Faculty7.setForeground(new java.awt.Color(0, 0, 0));
        Add_Faculty7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        Add_Faculty7.setText("Add Faculty");
        Add_Faculty7.setToolTipText("");
        Add_Faculty7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Add_Faculty7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Add_Faculty7.setkEndColor(new java.awt.Color(255, 255, 255));
        Add_Faculty7.setkForeGround(new java.awt.Color(0, 0, 0));
        Add_Faculty7.setkHoverColor(new java.awt.Color(0, 0, 0));
        Add_Faculty7.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Add_Faculty7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Add_Faculty7.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Add_Faculty7.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Add_Faculty7.setkStartColor(new java.awt.Color(255, 255, 255));
        Add_Faculty7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Faculty7ActionPerformed(evt);
            }
        });

        Manage_Faculty7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Manage_Faculty7.setForeground(new java.awt.Color(0, 0, 0));
        Manage_Faculty7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/project-management.png"))); // NOI18N
        Manage_Faculty7.setText("Manage Faculty");
        Manage_Faculty7.setToolTipText("");
        Manage_Faculty7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Manage_Faculty7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty7.setkEndColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty7.setkForeGround(new java.awt.Color(0, 0, 0));
        Manage_Faculty7.setkHoverColor(new java.awt.Color(0, 0, 0));
        Manage_Faculty7.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Manage_Faculty7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Manage_Faculty7.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Manage_Faculty7.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Manage_Faculty7.setkStartColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_Faculty7ActionPerformed(evt);
            }
        });

        Profile_Button7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Profile_Button7.setForeground(new java.awt.Color(0, 0, 0));
        Profile_Button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        Profile_Button7.setText("Profile");
        Profile_Button7.setToolTipText("");
        Profile_Button7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Profile_Button7.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Profile_Button7.setkEndColor(new java.awt.Color(255, 255, 255));
        Profile_Button7.setkForeGround(new java.awt.Color(0, 0, 0));
        Profile_Button7.setkHoverColor(new java.awt.Color(0, 0, 0));
        Profile_Button7.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Profile_Button7.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Profile_Button7.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Profile_Button7.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Profile_Button7.setkStartColor(new java.awt.Color(255, 255, 255));
        Profile_Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_Button7ActionPerformed(evt);
            }
        });

        Left_top7.setBackground(new java.awt.Color(75, 86, 210));
        Left_top7.setPreferredSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout Left_top7Layout = new javax.swing.GroupLayout(Left_top7);
        Left_top7.setLayout(Left_top7Layout);
        Left_top7Layout.setHorizontalGroup(
            Left_top7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Left_top7Layout.setVerticalGroup(
            Left_top7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Left_Panel7Layout = new javax.swing.GroupLayout(Left_Panel7);
        Left_Panel7.setLayout(Left_Panel7Layout);
        Left_Panel7Layout.setHorizontalGroup(
            Left_Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left_Panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Left_Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Manage_Faculty7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DashBoard7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logout7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profile_Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Faculty7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(Left_top7, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );
        Left_Panel7Layout.setVerticalGroup(
            Left_Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left_Panel7Layout.createSequentialGroup()
                .addComponent(Left_top7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(DashBoard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Add_Faculty7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Manage_Faculty7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Profile_Button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(583, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(Left_Panel7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Right_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Left_Panel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Right_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void DashBoard7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBoard7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashBoard7ActionPerformed

    private void Logout7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Logout7ActionPerformed

    private void Add_Faculty7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Faculty7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_Faculty7ActionPerformed

    private void Manage_Faculty7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Faculty7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_Faculty7ActionPerformed

    private void Profile_Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_Button7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_Button7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Faculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Faculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Add_Faculty;
    private com.k33ptoo.components.KButton Add_Faculty1;
    private com.k33ptoo.components.KButton Add_Faculty2;
    private com.k33ptoo.components.KButton Add_Faculty3;
    private com.k33ptoo.components.KButton Add_Faculty4;
    private com.k33ptoo.components.KButton Add_Faculty5;
    private com.k33ptoo.components.KButton Add_Faculty6;
    private com.k33ptoo.components.KButton Add_Faculty7;
    private com.k33ptoo.components.KButton DashBoard;
    private com.k33ptoo.components.KButton DashBoard1;
    private com.k33ptoo.components.KButton DashBoard2;
    private com.k33ptoo.components.KButton DashBoard3;
    private com.k33ptoo.components.KButton DashBoard4;
    private com.k33ptoo.components.KButton DashBoard5;
    private com.k33ptoo.components.KButton DashBoard6;
    private com.k33ptoo.components.KButton DashBoard7;
    private com.k33ptoo.components.KButton Delete;
    private javax.swing.JPanel Left_Panel;
    private javax.swing.JPanel Left_Panel1;
    private javax.swing.JPanel Left_Panel2;
    private javax.swing.JPanel Left_Panel3;
    private javax.swing.JPanel Left_Panel4;
    private javax.swing.JPanel Left_Panel5;
    private javax.swing.JPanel Left_Panel6;
    private javax.swing.JPanel Left_Panel7;
    private javax.swing.JPanel Left_top;
    private javax.swing.JPanel Left_top1;
    private javax.swing.JPanel Left_top2;
    private javax.swing.JPanel Left_top3;
    private javax.swing.JPanel Left_top4;
    private javax.swing.JPanel Left_top5;
    private javax.swing.JPanel Left_top6;
    private javax.swing.JPanel Left_top7;
    private com.k33ptoo.components.KButton Logout;
    private com.k33ptoo.components.KButton Logout1;
    private com.k33ptoo.components.KButton Logout2;
    private com.k33ptoo.components.KButton Logout3;
    private com.k33ptoo.components.KButton Logout4;
    private com.k33ptoo.components.KButton Logout5;
    private com.k33ptoo.components.KButton Logout6;
    private com.k33ptoo.components.KButton Logout7;
    private com.k33ptoo.components.KButton Manage_Faculty;
    private com.k33ptoo.components.KButton Manage_Faculty1;
    private com.k33ptoo.components.KButton Manage_Faculty2;
    private com.k33ptoo.components.KButton Manage_Faculty3;
    private com.k33ptoo.components.KButton Manage_Faculty4;
    private com.k33ptoo.components.KButton Manage_Faculty5;
    private com.k33ptoo.components.KButton Manage_Faculty6;
    private com.k33ptoo.components.KButton Manage_Faculty7;
    private com.k33ptoo.components.KButton Profile_Button;
    private com.k33ptoo.components.KButton Profile_Button1;
    private com.k33ptoo.components.KButton Profile_Button2;
    private com.k33ptoo.components.KButton Profile_Button3;
    private com.k33ptoo.components.KButton Profile_Button4;
    private com.k33ptoo.components.KButton Profile_Button5;
    private com.k33ptoo.components.KButton Profile_Button6;
    private com.k33ptoo.components.KButton Profile_Button7;
    private javax.swing.JPanel Right_Panel;
    private javax.swing.JPanel Title;
    private com.k33ptoo.components.KButton Update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
