/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package faculty;

/**
 *
 * @author HP
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Left_Panel = new javax.swing.JPanel();
        DashBoard = new com.k33ptoo.components.KButton();
        Logout = new com.k33ptoo.components.KButton();
        Add_Faculty = new com.k33ptoo.components.KButton();
        Manage_Faculty = new com.k33ptoo.components.KButton();
        Profile_Button = new com.k33ptoo.components.KButton();
        Left_top = new javax.swing.JPanel();
        Right_Panel = new javax.swing.JPanel();
        Right_Title = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        Profile = new java.awt.Panel();
        Edit = new com.k33ptoo.components.KButton();
        Change = new com.k33ptoo.components.KButton();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        Name = new java.awt.Label();
        Email = new java.awt.Label();
        Dob = new java.awt.Label();
        Gender = new java.awt.Label();
        Age = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 900));

        Left_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Left_Panel.setPreferredSize(new java.awt.Dimension(300, 900));

        DashBoard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DashBoard.setForeground(new java.awt.Color(0, 0, 0));
        DashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home (1).png"))); // NOI18N
        DashBoard.setText("DashBoard");
        DashBoard.setToolTipText("");
        DashBoard.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        DashBoard.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        DashBoard.setkEndColor(new java.awt.Color(255, 255, 255));
        DashBoard.setkForeGround(new java.awt.Color(0, 0, 0));
        DashBoard.setkHoverColor(new java.awt.Color(0, 0, 0));
        DashBoard.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        DashBoard.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        DashBoard.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        DashBoard.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        DashBoard.setkStartColor(new java.awt.Color(255, 255, 255));
        DashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashBoardActionPerformed(evt);
            }
        });

        Logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logout.setForeground(new java.awt.Color(0, 0, 0));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.setToolTipText("");
        Logout.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Logout.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Logout.setkEndColor(new java.awt.Color(255, 255, 255));
        Logout.setkForeGround(new java.awt.Color(0, 0, 0));
        Logout.setkHoverColor(new java.awt.Color(0, 0, 0));
        Logout.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Logout.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Logout.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Logout.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Logout.setkStartColor(new java.awt.Color(255, 255, 255));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Add_Faculty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Add_Faculty.setForeground(new java.awt.Color(0, 0, 0));
        Add_Faculty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        Add_Faculty.setText("Add Faculty");
        Add_Faculty.setToolTipText("");
        Add_Faculty.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Add_Faculty.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Add_Faculty.setkEndColor(new java.awt.Color(255, 255, 255));
        Add_Faculty.setkForeGround(new java.awt.Color(0, 0, 0));
        Add_Faculty.setkHoverColor(new java.awt.Color(0, 0, 0));
        Add_Faculty.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Add_Faculty.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Add_Faculty.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Add_Faculty.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Add_Faculty.setkStartColor(new java.awt.Color(255, 255, 255));
        Add_Faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_FacultyActionPerformed(evt);
            }
        });

        Manage_Faculty.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Manage_Faculty.setForeground(new java.awt.Color(0, 0, 0));
        Manage_Faculty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/project-management.png"))); // NOI18N
        Manage_Faculty.setText("Manage Faculty");
        Manage_Faculty.setToolTipText("");
        Manage_Faculty.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Manage_Faculty.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty.setkEndColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty.setkForeGround(new java.awt.Color(0, 0, 0));
        Manage_Faculty.setkHoverColor(new java.awt.Color(0, 0, 0));
        Manage_Faculty.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Manage_Faculty.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Manage_Faculty.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Manage_Faculty.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Manage_Faculty.setkStartColor(new java.awt.Color(255, 255, 255));
        Manage_Faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_FacultyActionPerformed(evt);
            }
        });

        Profile_Button.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Profile_Button.setForeground(new java.awt.Color(0, 0, 0));
        Profile_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user.png"))); // NOI18N
        Profile_Button.setText("Profile");
        Profile_Button.setToolTipText("");
        Profile_Button.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Profile_Button.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Profile_Button.setkEndColor(new java.awt.Color(255, 255, 255));
        Profile_Button.setkForeGround(new java.awt.Color(0, 0, 0));
        Profile_Button.setkHoverColor(new java.awt.Color(0, 0, 0));
        Profile_Button.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Profile_Button.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Profile_Button.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Profile_Button.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Profile_Button.setkStartColor(new java.awt.Color(255, 255, 255));
        Profile_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButtonActionPerformed(evt);
            }
        });

        Left_top.setBackground(new java.awt.Color(75, 86, 210));
        Left_top.setPreferredSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout Left_topLayout = new javax.swing.GroupLayout(Left_top);
        Left_top.setLayout(Left_topLayout);
        Left_topLayout.setHorizontalGroup(
            Left_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Left_topLayout.setVerticalGroup(
            Left_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Left_PanelLayout = new javax.swing.GroupLayout(Left_Panel);
        Left_Panel.setLayout(Left_PanelLayout);
        Left_PanelLayout.setHorizontalGroup(
            Left_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Left_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Manage_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profile_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(Left_top, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );
        Left_PanelLayout.setVerticalGroup(
            Left_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left_PanelLayout.createSequentialGroup()
                .addComponent(Left_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(DashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Add_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Manage_Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Profile_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(583, Short.MAX_VALUE))
        );

        Right_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Right_Panel.setPreferredSize(new java.awt.Dimension(1300, 900));

        Right_Title.setPreferredSize(new java.awt.Dimension(1300, 200));

        label1.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        label1.setText("Faculty Managment System");

        javax.swing.GroupLayout Right_TitleLayout = new javax.swing.GroupLayout(Right_Title);
        Right_Title.setLayout(Right_TitleLayout);
        Right_TitleLayout.setHorizontalGroup(
            Right_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right_TitleLayout.createSequentialGroup()
                .addContainerGap(394, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );
        Right_TitleLayout.setVerticalGroup(
            Right_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_TitleLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        Edit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Edit.setForeground(new java.awt.Color(0, 0, 0));
        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/editing.png"))); // NOI18N
        Edit.setText("Edit Profile");
        Edit.setToolTipText("");
        Edit.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Edit.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Edit.setkEndColor(new java.awt.Color(255, 255, 255));
        Edit.setkForeGround(new java.awt.Color(0, 0, 0));
        Edit.setkHoverColor(new java.awt.Color(0, 0, 0));
        Edit.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Edit.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Edit.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Edit.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Edit.setkStartColor(new java.awt.Color(255, 255, 255));
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Change.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Change.setForeground(new java.awt.Color(0, 0, 0));
        Change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/password.png"))); // NOI18N
        Change.setText("Change Password");
        Change.setToolTipText("");
        Change.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        Change.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        Change.setkEndColor(new java.awt.Color(255, 255, 255));
        Change.setkForeGround(new java.awt.Color(0, 0, 0));
        Change.setkHoverColor(new java.awt.Color(0, 0, 0));
        Change.setkHoverEndColor(new java.awt.Color(191, 234, 245));
        Change.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        Change.setkHoverStartColor(new java.awt.Color(191, 234, 245));
        Change.setkIndicatorColor(new java.awt.Color(75, 86, 210));
        Change.setkStartColor(new java.awt.Color(255, 255, 255));
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        label2.setText("Profile");

        label3.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        label3.setText("Email_Id:");

        label4.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        label4.setText("Name:");

        label5.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        label5.setText("Date Of Birth:");

        label6.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        label6.setText("Gender:");

        label7.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        label7.setText("Age:");

        Name.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N

        Email.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N

        Dob.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N

        Gender.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N

        Age.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                                    .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(37, 37, 37))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                                    .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Age, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(Dob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Gender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                        .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Change, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(159, 159, 159)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(642, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Right_PanelLayout = new javax.swing.GroupLayout(Right_Panel);
        Right_Panel.setLayout(Right_PanelLayout);
        Right_PanelLayout.setHorizontalGroup(
            Right_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Right_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(386, 386, 386))
        );
        Right_PanelLayout.setVerticalGroup(
            Right_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Right_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Left_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Right_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1301, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Left_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Right_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashBoardActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void Add_FacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_FacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_FacultyActionPerformed

    private void Manage_FacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_FacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_FacultyActionPerformed

    private void Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_ButtonActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditActionPerformed

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton Add_Faculty;
    private java.awt.Label Age;
    private com.k33ptoo.components.KButton Change;
    private com.k33ptoo.components.KButton DashBoard;
    private java.awt.Label Dob;
    private com.k33ptoo.components.KButton Edit;
    private java.awt.Label Email;
    private java.awt.Label Gender;
    private javax.swing.JPanel Left_Panel;
    private javax.swing.JPanel Left_top;
    private com.k33ptoo.components.KButton Logout;
    private com.k33ptoo.components.KButton Manage_Faculty;
    private java.awt.Label Name;
    private java.awt.Panel Profile;
    private com.k33ptoo.components.KButton Profile_Button;
    private javax.swing.JPanel Right_Panel;
    private javax.swing.JPanel Right_Title;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables
}
